### ISSUE TITLE
Linux Mint support

### ISSUE THREAD

**Issue by schrammalama** [Etaash-mathamsetty/trigger-control#5] opened 2022-03-31 16:35 UTC
When I try to run the AppImage I get this error:
trigger-control: error while loading shared libraries: libGLEW.so.2.2: cannot open shared object file: No such file or directory

My first thought was that my libglew library is out of date so I ran "ls /usr/lib/x86_64-linux-gnu/ | grep libGLEW" and it said I'm running libGLEW 2.1 and not 2.2, but I looked into it and everything says 2.1 is the latest. Any idea whats going on?

**Comment by Etaash-mathamsetty** [comment] 2022-03-31 23:03
what distro are you using?
I'm using arch linux which is rolling release so my packages are way too new to make a working app image for everyone. (this limitation I cannot bypass without some kind of chroot or vm)
so basically, for the app image to work, you would need a new enough system. (not ubuntu 20.04 or debian stable or smth)

**Comment by schrammalama** [comment] 2022-04-01 15:42
Thanks for your response, I am using Linux Mint 20.3. Before trying the app image I tried to compile it and installed all the dependency and got this response:
`g++ -lusb -lSDL2 -lhidapi-hidraw -lGL -lGLEW -I/usr/include/SDL2 -o trigger-control trigger-control.o imgui.o imgui_impl_opengl3.o imgui_impl_sdl.o imgui_demo.o imgui_draw.o imgui_tables.o imgui_widgets.o
/usr/bin/ld: imgui_impl_opengl3.o: in function `open_libgl':
imgui_impl_opengl3.cpp:(.text+0x21): undefined reference to `dlopen'
/usr/bin/ld: imgui_impl_opengl3.cpp:(.text+0x3c): undefined reference to `dlsym'
/usr/bin/ld: imgui_impl_opengl3.o: in function `close_libgl':
imgui_impl_opengl3.cpp:(.text+0xc): undefined reference to `dlclose'
/usr/bin/ld: imgui_impl_opengl3.o: in function `get_proc':
imgui_impl_opengl3.cpp:(.text+0x384): undefined reference to `dlsym'
/usr/bin/ld: imgui_impl_sdl.o: in function `ImGui_ImplSDL2_GetClipboardText(void*)':
imgui_impl_sdl.cpp:(.text+0x37): undefined reference to `SDL_free'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x3c): undefined reference to `SDL_GetClipboardText'
/usr/bin/ld: imgui_impl_sdl.o: in function `ImGui_ImplSDL2_Init(SDL_Window*, SDL_Renderer*)':
imgui_impl_sdl.cpp:(.text+0xac): undefined reference to `SDL_GetCurrentVideoDriver'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1b9): undefined reference to `SDL_CreateSystemCursor'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1c7): undefined reference to `SDL_CreateSystemCursor'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1d5): undefined reference to `SDL_CreateSystemCursor'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1e3): undefined reference to `SDL_CreateSystemCursor'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1f1): undefined reference to `SDL_CreateSystemCursor'
/usr/bin/ld: imgui_impl_sdl.o:imgui_impl_sdl.cpp:(.text+0x1ff): more undefined references to `SDL_CreateSystemCursor' follow
/usr/bin/ld: imgui_impl_sdl.o: in function `ImGui_ImplSDL2_Init(SDL_Window*, SDL_Renderer*)':
imgui_impl_sdl.cpp:(.text+0x240): undefined reference to `SDL_SetHint'
/usr/bin/ld: imgui_impl_sdl.o: in function `ImGui_ImplSDL2_Shutdown()':
imgui_impl_sdl.cpp:(.text+0xb1e): undefined reference to `SDL_free'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xb38): undefined reference to `SDL_FreeCursor'
/usr/bin/ld: imgui_impl_sdl.o: in function `ImGui_ImplSDL2_NewFrame()':
imgui_impl_sdl.cpp:(.text+0xbd3): undefined reference to `SDL_GetWindowSize'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xbdc): undefined reference to `SDL_GetWindowFlags'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xc00): undefined reference to `SDL_GetRendererOutputSize'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xc7f): undefined reference to `SDL_GetPerformanceCounter'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xcf4): undefined reference to `SDL_CaptureMouse'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xcf9): undefined reference to `SDL_GetKeyboardFocus'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xd67): undefined reference to `SDL_GameControllerOpen'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xd80): undefined reference to `SDL_GameControllerGetButton'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xda1): undefined reference to `SDL_GameControllerGetButton'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xdbf): undefined reference to `SDL_GameControllerGetButton'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xde0): undefined reference to `SDL_GameControllerGetButton'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xe01): undefined reference to `SDL_GameControllerGetButton'
/usr/bin/ld: imgui_impl_sdl.o:imgui_impl_sdl.cpp:(.text+0xe22): more undefined references to `SDL_GameControllerGetButton' follow
/usr/bin/ld: imgui_impl_sdl.o: in function `ImGui_ImplSDL2_NewFrame()':
imgui_impl_sdl.cpp:(.text+0xf09): undefined reference to `SDL_GameControllerGetAxis'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xf5b): undefined reference to `SDL_GameControllerGetAxis'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xfad): undefined reference to `SDL_GameControllerGetButton'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xfce): undefined reference to `SDL_GameControllerGetButton'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xfec): undefined reference to `SDL_GameControllerGetAxis'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1040): undefined reference to `SDL_GameControllerGetAxis'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1097): undefined reference to `SDL_GameControllerGetAxis'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x10ee): undefined reference to `SDL_GameControllerGetAxis'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1145): undefined reference to `SDL_GameControllerGetAxis'
/usr/bin/ld: imgui_impl_sdl.o:imgui_impl_sdl.cpp:(.text+0x119c): more undefined references to `SDL_GameControllerGetAxis' follow
/usr/bin/ld: imgui_impl_sdl.o: in function `ImGui_ImplSDL2_NewFrame()':
imgui_impl_sdl.cpp:(.text+0x12d1): undefined reference to `SDL_SetCursor'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x12db): undefined reference to `SDL_ShowCursor'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1317): undefined reference to `SDL_GetGlobalMouseState'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x132a): undefined reference to `SDL_GetWindowPosition'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1365): undefined reference to `SDL_GL_GetDrawableSize'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1373): undefined reference to `SDL_ShowCursor'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x13c1): undefined reference to `SDL_GetPerformanceFrequency'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x14a8): undefined reference to `SDL_WarpMouseInWindow'
/usr/bin/ld: imgui_impl_sdl.o: in function `ImGui_ImplSDL2_SetClipboardText(void*, char const*)':
imgui_impl_sdl.cpp:(.text+0x58): undefined reference to `SDL_SetClipboardText'
/usr/bin/ld: trigger-control.o: in function `main':
trigger-control.cpp:(.text.startup+0x29): undefined reference to `hid_init'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x33): undefined reference to `SDL_Init'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x54): undefined reference to `SDL_CreateWindow'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x6f): undefined reference to `SDL_GL_CreateContext'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x85): undefined reference to `SDL_GL_MakeCurrent'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0xb8): undefined reference to `SDL_CreateRGBSurfaceWithFormatFrom'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0xc6): undefined reference to `SDL_SetWindowIcon'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0xce): undefined reference to `SDL_FreeSurface'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0xd4): undefined reference to `glewExperimental'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0xda): undefined reference to `glewInit'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x13c): undefined reference to `hid_enumerate'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x1ad): undefined reference to `hid_free_enumeration'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x1b5): undefined reference to `hid_open_path'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x1ff): undefined reference to `hid_get_feature_report'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x4a7): undefined reference to `SDL_PollEvent'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x4bf): undefined reference to `SDL_GetWindowSize'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x4d6): undefined reference to `glViewport'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x4e9): undefined reference to `glClearColor'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x4f3): undefined reference to `glClear'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x99b): undefined reference to `SDL_GL_SwapWindow'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x9c2): undefined reference to `SDL_GL_DeleteContext'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0x9cc): undefined reference to `SDL_DestroyWindow'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0xac3): undefined reference to `hid_write'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0xad8): undefined reference to `hid_error'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0xbcb): undefined reference to `hid_write'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0xc43): undefined reference to `hid_error'
/usr/bin/ld: trigger-control.cpp:(.text.startup+0xc93): undefined reference to `SDL_ShowSimpleMessageBox'
collect2: error: ld returned 1 exit status
make: *** [Makefile:24: trigger-control] Error 1
`
I'll try installing glew 2.2 and try out the AppImage again and I'll also try figuring out the compling.

**Comment by Etaash-mathamsetty** [comment] 2022-04-01 21:19
ok, you have to install lets say (for headers)
sudo apt-get install libglew-dev 
AND (for .so files)
sudo apt-get install libglew 
I am pretty sure that when installing 
if you have done this correctly, it should compile. 
Another think to check for is if `/usr/lib` contains these libraries
if it contains SDL2 and all the other libraries, you should be good
if /usr/lib does contain these libraries u can try adding `-L/usr/lib` into the `LIBRARIES` section of the make file and see if it works

**Comment by schrammalama** [comment] 2022-04-04 18:34
I tried to install them and they all said I had the latest of them installed, I also tried adding to the make file and get same error

**Comment by Etaash-mathamsetty** [comment] 2022-04-04 19:09
Try building it from live usb (make sure to install the -dev libraries) and see if that fixes it, also try googling on the internet and see what would could cause the problem. I honestly don't know why you can't build.

**Comment by Etaash-mathamsetty** [comment] 2022-04-12 20:37
any success?

**Comment by schrammalama** [comment] 2022-04-12 20:38
nope, not yet

**Comment by Etaash-mathamsetty** [comment] 2022-04-13 02:29
well this came back and it bit me in the butt, so I was trying to cross compile for windows and you can guess what happened...

**Comment by Etaash-mathamsetty** [comment] 2022-04-13 02:43
alright 99% can confirm latest master fixes it (but I won't close this issue yet)

**Comment by schrammalama** [comment] 2022-04-14 13:47
Tried the new master got a new error:
g++ -c -O2 -Wall   `pkg-config --libs --cflags SDL2_mixer` `pkg-config --cflags --libs hidapi-hidraw` `pkg-config --cflags --libs glew` `pkg-config --libs --cflags glib-2.0` -Wl,--no-as-needed -ldl -o trigger-control.o /home/schrammalama/trigger-control/trigger-control.cpp
/home/schrammalama/trigger-control/trigger-control.cpp: In function ‘void CenteredText(const char*)’:
/home/schrammalama/trigger-control/trigger-control.cpp:106:18: warning: format not a string literal and no format arguments [-Wformat-security]
  106 |  ImGui::Text(text);
      |                  ^
/home/schrammalama/trigger-control/trigger-control.cpp: In function ‘int main(int, char**)’:
/home/schrammalama/trigger-control/trigger-control.cpp:486:32: error: ‘std::filesystem’ has not been declared
  486 |    for(const auto& file : std::filesystem::directory_iterator(CONFIG_PATH)){
      |                                ^~~~~~~~~~
/home/schrammalama/trigger-control/trigger-control.cpp:557:32: error: ‘std::filesystem’ has not been declared
  557 |    for(const auto& file : std::filesystem::directory_iterator(CONFIG_PATH)){
      |                                ^~~~~~~~~~
/home/schrammalama/trigger-control/trigger-control.cpp:619:32: error: ‘std::filesystem’ has not been declared
  619 |    for(const auto& file : std::filesystem::directory_iterator(CONFIG_PATH)){
      |                                ^~~~~~~~~~
/home/schrammalama/trigger-control/trigger-control.cpp: In function ‘void load_preset(uint8_t*, bool, const char*)’:
/home/schrammalama/trigger-control/trigger-control.cpp:72:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   72 |   fread(outReport + 11 + bt, sizeof(*outReport), 30 -10, f);
      |   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:16: trigger-control.o] Error 1

**Comment by Etaash-mathamsetty** [comment] 2022-04-14 15:17
> Tried the new master got a new error: g++ -c -O2 -Wall `pkg-config --libs --cflags SDL2_mixer` `pkg-config --cflags --libs hidapi-hidraw` `pkg-config --cflags --libs glew` `pkg-config --libs --cflags glib-2.0` -Wl,--no-as-needed -ldl -o trigger-control.o /home/schrammalama/trigger-control/trigger-control.cpp /home/schrammalama/trigger-control/trigger-control.cpp: In function ‘void CenteredText(const char*)’: /home/schrammalama/trigger-control/trigger-control.cpp:106:18: warning: format not a string literal and no format arguments [-Wformat-security] 106 | ImGui::Text(text); | ^ /home/schrammalama/trigger-control/trigger-control.cpp: In function ‘int main(int, char**)’: /home/schrammalama/trigger-control/trigger-control.cpp:486:32: error: ‘std::filesystem’ has not been declared 486 | for(const auto& file : std::filesystem::directory_iterator(CONFIG_PATH)){ | ^~~~~~~~~~ /home/schrammalama/trigger-control/trigger-control.cpp:557:32: error: ‘std::filesystem’ has not been declared 557 | for(const auto& file : std::filesystem::directory_iterator(CONFIG_PATH)){ | ^~~~~~~~~~ /home/schrammalama/trigger-control/trigger-control.cpp:619:32: error: ‘std::filesystem’ has not been declared 619 | for(const auto& file : std::filesystem::directory_iterator(CONFIG_PATH)){ | ^~~~~~~~~~ /home/schrammalama/trigger-control/trigger-control.cpp: In function ‘void load_preset(uint8_t*, bool, const char*)’: /home/schrammalama/trigger-control/trigger-control.cpp:72:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result] 72 | fread(outReport + 11 + bt, sizeof(*outReport), 30 -10, f); | ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ make: *** [Makefile:16: trigger-control.o] Error 1

that is caused by your compiler being out of date and not using c++17 by default 
This is why I don't use ubuntu based distros btw

**Comment by Etaash-mathamsetty** [comment] 2022-04-14 15:20
ok I fixed the makefile, try now

**Comment by schrammalama** [comment] 2022-04-14 15:43
I'm able to compile but this shows up:
/home/schrammalama/trigger-control/trigger-control.cpp: In function ‘void CenteredText(const char*)’:
/home/schrammalama/trigger-control/trigger-control.cpp:106:18: warning: format not a string literal and no format arguments [-Wformat-security]
  106 |  ImGui::Text(text);
      |                  ^
/home/schrammalama/trigger-control/trigger-control.cpp: In function ‘void load_preset(uint8_t*, bool, const char*)’:
/home/schrammalama/trigger-control/trigger-control.cpp:72:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   72 |   fread(outReport + 11 + bt, sizeof(*outReport), 30 -10, f);
      |   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

When I try to run the program with ./trigger-control a window opens for a second then closes and the terminal says:
Segmentation Fault(core dumped)
I looked it up and found that it means the program tried to access memory that it didn't have access to

**Comment by Etaash-mathamsetty** [comment] 2022-04-14 15:55
> I'm able to compile but this shows up: /home/schrammalama/trigger-control/trigger-control.cpp: In function ‘void CenteredText(const char*)’: /home/schrammalama/trigger-control/trigger-control.cpp:106:18: warning: format not a string literal and no format arguments [-Wformat-security] 106 | ImGui::Text(text); | ^ /home/schrammalama/trigger-control/trigger-control.cpp: In function ‘void load_preset(uint8_t*, bool, const char*)’: /home/schrammalama/trigger-control/trigger-control.cpp:72:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result] 72 | fread(outReport + 11 + bt, sizeof(*outReport), 30 -10, f); | ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> When I try to run the program with ./trigger-control a window opens for a second then closes and the terminal says: Segmentation Fault(core dumped) I looked it up and found that it means the program tried to access memory that it didn't have access to

those are warnings, but I have to investigate that segfault though

**Comment by schrammalama** [comment] 2022-04-14 16:08
[file.txt](https://github.com/Etaash-mathamsetty/trigger-control/files/8490678/file.txt)

**Comment by Etaash-mathamsetty** [comment] 2022-04-14 16:12
when was the last time you updated your system?
with like `apt-get update && apt-get upgrade`
gcc 9.3 and kernel 5.4.0-96 are like caveman era stuff lmao

**Comment by schrammalama** [comment] 2022-04-14 16:15
I'm pretty sure I upgraded recently but I'll try again

**Comment by Etaash-mathamsetty** [comment] 2022-04-14 16:19
also you can try using the debug build to figure out what went wrong I edited one of my earlier comments with the instructions on how to use it

**Comment by schrammalama** [comment] 2022-04-14 16:20
I ran the commands and restarted, still get the error when running the program. Here's a new dmesg file:
[file1.txt](https://github.com/Etaash-mathamsetty/trigger-control/files/8490753/file1.txt)

**Comment by Etaash-mathamsetty** [comment] 2022-04-14 16:23
the segfault is happening in hidapi, what version is it? 
and you can use the debug makefile to figure out where in hidapi's code its segfaulting. (easily could be something the hidapi guys fixed a while back)

**Comment by schrammalama** [comment] 2022-04-14 16:30
None of the commands I know to check the version are working

**Comment by Etaash-mathamsetty** [comment] 2022-04-14 16:33
just use apt search hidapi, it should show you a version

**Comment by Etaash-mathamsetty** [comment] 2022-04-14 16:47
> 

did it show a version though?

**Comment by schrammalama** [comment] 2022-04-14 17:20
It did not work

**Comment by Etaash-mathamsetty** [comment] 2022-04-14 17:33
try 
`dpkg -l | grep hidapi`

**Comment by Etaash-mathamsetty** [comment] 2022-04-15 02:00
im creating a usb image of linux mint, i'll try it on that and see what happens...

**Comment by Etaash-mathamsetty** [comment] 2022-04-15 02:32
`0x00007ffff7e3745f in hid_get_feature_report () from /lib/x86_64-linux-gnu/libhidapi-hidraw.so.0`
ok found the culprit, its that hid_get_feature_report in the beginning.

**Comment by Etaash-mathamsetty** [comment] 2022-04-15 02:41
I don't think there is a way to fix this issue, even after compiling it from scratch it still doesn't seem to work, I think the best bet is to wait for linux mint 21 or something.

**Comment by Etaash-mathamsetty** [comment] 2022-04-15 03:14
I removed hid_get_feature_report, and replaced it with something else, you should no longer have a segfault

**Comment by schrammalama** [comment] 2022-04-15 15:36
I tried the new master and still get the same error

**Comment by Etaash-mathamsetty** [comment] 2022-04-15 17:08
> I tried the new master and still get the same error

must be a segfault somewhere else, time for liveusb again!

**Comment by Etaash-mathamsetty** [comment] 2022-04-15 17:19
`0x00007ffff7e373c4 in hid_read ()
   from /lib/x86_64-linux-gnu/libhidapi-hidraw.so.0`
im sorry, but this is unfixable

**Comment by Etaash-mathamsetty** [comment] 2022-04-15 17:21
solution: wait for linux mint 21 and if it dosen't work there, I am open to investigate...

**Comment by Etaash-mathamsetty** [comment] 2022-04-16 03:52
> `0x00007ffff7e373c4 in hid_read () from /lib/x86_64-linux-gnu/libhidapi-hidraw.so.0` im sorry, but this is unfixable, if I get rid of hid_read, its gonna segfault on hid_write, there's nothing I can do about this

tried it on ubuntu 22.04 (on another computer), same issue, so I removed hid_read and it works fine surprisingly

**Comment by Etaash-mathamsetty** [comment] 2022-04-17 17:04
does it work for you now?

**Comment by schrammalama** [comment] 2022-04-18 15:39
Still not working sadly

**Comment by Etaash-mathamsetty** [comment] 2022-04-19 22:35
> Still not working sadly 

It works fine on Ubuntu 22.04 though...
I would suggest to distro hop or wait till the next Linux mint release
This issue is just not in my power to solve. (It is segfaulting in some dependency like hidapi, since it works fine on both Ubuntu and arch)
I'll flash an Ubuntu 20.04 install disk and see if it works on that

**Comment by schrammalama** [comment] 2022-04-20 15:53
This is what I got
Thread 1 "trigger-control" received signal SIGSEGV, Segmentation fault.
__wcscmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
101	../sysdeps/x86_64/multiarch/strcmp-avx2.S: No such file or directory.

**Comment by Etaash-mathamsetty** [comment] 2022-04-20 19:56
> This is what I got Thread 1 "trigger-control" received signal SIGSEGV, Segmentation fault. __wcscmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101 101 ../sysdeps/x86_64/multiarch/strcmp-avx2.S: No such file or directory.

something about your system is really f*cked up then, cuz you are crashing on strcmp, which is a regular function in the C standard library

**Comment by Etaash-mathamsetty** [comment] 2022-04-20 20:10
try latest master

**Comment by schrammalama** [comment] 2022-04-22 15:07
It runs!!
Sadly I cant get it to work. Changing the settings and pressing Apply does nothing

**Comment by Etaash-mathamsetty** [comment] 2022-04-22 19:25
> It runs!! Sadly I cant get it to work. Changing the settings and pressing Apply does nothing

are you actually kidding me...

**Comment by Etaash-mathamsetty** [comment] 2022-04-26 21:38
any luck?

**Comment by Etaash-mathamsetty** [comment] 2022-04-30 00:00
any luck now?
I switched to sdl2, no more hidapi garbage

**Comment by Etaash-mathamsetty** [comment] 2022-05-10 21:25
I am going to close this, since there's no reason for this not to work, create a new issue if it's not working for you.

**Closed by Etaash-mathamsetty** 2022-05-10 21:25 UTC
